exclude: ^(.*assets|.*_pb2\.py|.*_pb2\.pyi|.*_pb2_grpc\.py)
default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: check-merge-conflict

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.11.0-1
    hooks:
      - id: shfmt
        args: [--indent, "2", --write]
        stages: [pre-commit]

  - repo: https://github.com/mrtazz/checkmake.git
    rev: 0.2.2
    hooks:
      - id: checkmake
        args: [--config, "./.checkmake.ini"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: dir_checker
        name: validate directories
        language: python
        entry: env PYTHONPATH=. python scripts/dir_checker/main.py
        pass_filenames: false

  - repo: local
    hooks:
      - id: python_checker
        name: validate python files
        language: python
        entry: env PYTHONPATH=. python scripts/python_checker/main.py

  - repo: local
    hooks:
      - id: compose_checker
        name: validate docker compose files
        language: script
        entry: scripts/compose_checker/main.sh
        args: [--env-file, "./settings/compose/.env"]
        require_serial: true
        files: (docker-)?compose.*\.ya?ml$

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker

  - repo: https://github.com/pycqa/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: [--configfile, "pyproject.toml", --recursive, "."]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests==2.32.0.20250328]

  - repo: https://github.com/pycqa/pylint
    rev: v3.3.6
    hooks:
      - id: pylint
