exclude: ^(.*assets|.*_pb2\.py|.*_pb2\.pyi|.*_pb2_grpc\.py|\.venv)
default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-xml
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: check-merge-conflict
      - id: check-added-large-files
        stages: [pre-commit]
      - id: check-executables-have-shebangs
        stages: [pre-commit]
      - id: check-shebang-scripts-are-executable
        stages: [pre-commit]
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-symlinks

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt
        args: [--indent, "2", --write]
        stages: [pre-commit]

  - repo: https://github.com/mrtazz/checkmake.git
    rev: 0.2.2
    hooks:
      - id: checkmake
        args: [--config, "./.checkmake.ini"]

  - repo: https://github.com/ahmadiehsan/fixmate
    rev: 2.0.2
    hooks:
      - id: dir_checker
      - id: compose_checker
        args: [--env-file, "./settings/compose/.env"]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker

  - repo: https://github.com/ddanier/sub-pre-commit.git
    rev: v4.3.0
    hooks:
      - id: sub-pre-commit
        name: "pre-commit for service_1"
        args: [-p, "apps/service_1"]
        files: "^apps/service_1/.*"
      - id: sub-pre-commit
        name: "pre-commit for service_2"
        args: [-p, "apps/service_2"]
        files: "^apps/service_2/.*"
      - id: sub-pre-commit
        name: "pre-commit for protos"
        args: [-p, "apps/protos"]
        files: "^apps/protos/.*"
