exclude: ^(.*assets|.*_pb2\.py|.*_pb2\.pyi|.*_pb2_grpc\.py|\.venv)
default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: check-merge-conflict

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.11.0-1
    hooks:
      - id: shfmt
        args: [--indent, "2", --write]
        stages: [pre-commit]

  - repo: https://github.com/mrtazz/checkmake.git
    rev: 0.2.2
    hooks:
      - id: checkmake
        args: [--config, "./.checkmake.ini"]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.14
    hooks:
      - id: uv-lock
        name: uv-lock (service_1)
        args: [--project, "./apps/service_1"]
        files: apps/service_1/pyproject.toml
      - id: uv-lock
        name: uv-lock (service_2)
        args: [--project, "./apps/service_2"]
        files: apps/service_2/pyproject.toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
      - id: ruff
        name: ruff (service_1)
        args: [--config, "./apps/service_1/pyproject.toml"]
        files: ^apps/service_1/.*\.py
      - id: ruff-format
        name: ruff-format (service_1)
        args: [--config, "./apps/service_1/pyproject.toml"]
        files: ^apps/service_1/.*\.py
      - id: ruff
        name: ruff (service_2)
        args: [--config, "./apps/service_2/pyproject.toml"]
        files: ^apps/service_2/.*\.py
      - id: ruff-format
        name: ruff-format (service_2)
        args: [--config, "./apps/service_2/pyproject.toml"]
        files: ^apps/service_2/.*\.py

  - repo: https://github.com/ahmadiehsan/fixmate
    rev: 1.1.0
    hooks:
      - id: dir_checker
        name: dir_checker (service_1)
        args: [--config, "./apps/service_1/pyproject.toml"]
      - id: python_checker
        name: python_checker (service_1)
        args: [--config, "./apps/service_1/pyproject.toml"]
        files: ^apps/service_1/.*\.py
      - id: dir_checker
        name: dir_checker (service_2)
        args: [--config, "./apps/service_2/pyproject.toml"]
      - id: python_checker
        name: python_checker (service_2)
        args: [--config, "./apps/service_2/pyproject.toml"]
        files: ^apps/service_2/.*\.py
      - id: dir_checker
        name: dir_checker (protos)
      - id: compose_checker
        args: [--env-file, "./settings/compose/.env"]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        name: mypy (service_1)
        args:
          [
            --ignore-missing-imports,
            --scripts-are-modules,
            --config-file,
            "./apps/service_1/pyproject.toml",
          ]
        files: ^apps/service_1/.*\.py
        additional_dependencies: [types-requests==2.32.0.20250328]
      - id: mypy
        name: mypy (service_2)
        args:
          [
            --ignore-missing-imports,
            --scripts-are-modules,
            --config-file,
            "./apps/service_2/pyproject.toml",
          ]
        files: ^apps/service_2/.*\.py

  - repo: https://github.com/pycqa/pylint
    rev: v3.3.6
    hooks:
      - id: pylint
        name: pylint (service_1)
        args: [--rcfile, "./apps/service_1/pyproject.toml"]
        files: ^apps/service_1/.*\.py
      - id: pylint
        name: pylint (service_2)
        args: [--rcfile, "./apps/service_2/pyproject.toml"]
        files: ^apps/service_2/.*\.py
