services:
  nginx:
    restart: always

  kong:
    restart: always

  otel_collector:
    restart: always

  elasticsearch:
    restart: always

  kibana:
    restart: always

  prometheus:
    restart: always

  grafana:
    restart: always

  jaeger:
    restart: always

  kafka:
    restart: always

  service_1:
    build:
      context: ./src/service_1
      target: prod
    restart: always

  service_2:
    build:
      context: ./src/service_2
      target: prod
    restart: always
