services:
  nginx:
    image: ${NGINX_IMAGE}
    hostname: ${NGINX_HOST}
    ports:
      - ${NGINX_PORT_PUBLIC}:${NGINX_PORT}
    env_file:
      - ./settings/docker_compose/.env
    volumes:
      - ./settings/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro

  kong:
    image: ${KONG_IMAGE}
    hostname: ${KONG_HOST}
    ports:
      - ${KONG_PORT}
    env_file:
      - ./settings/docker_compose/.env
      - ./settings/kong/.env
    volumes:
      - ./settings/kong/config.yaml.template:/etc/config.yaml.template:ro
      - ./settings/kong/entrypoint.sh:/etc/entrypoint.sh:ro
      - ./settings/docker_compose/wait:/etc/wait:ro
    entrypoint: /etc/entrypoint.sh
    user: root
    depends_on:
      - nginx

  otel_collector:
    image: ${OTEL_COLLECTOR_IMAGE}
    hostname: ${OTEL_COLLECTOR_HOST}
    ports:
      - ${OTEL_COLLECTOR_GRPC_PORT}
      - ${OTEL_COLLECTOR_HTTP_PORT}
    env_file:
      - ./settings/docker_compose/.env
    volumes:
      - ./settings/otel_collector/config.yaml:/etc/otelcol-contrib/config.yaml:ro
    depends_on:
      - elasticsearch
      - prometheus
      - jaeger

  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE}
    hostname: ${ELASTICSEARCH_HOST}
    ports:
      - ${ELASTICSEARCH_PORT}
    env_file:
      - ./settings/docker_compose/.env
      - ./settings/elasticsearch/.env
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: curl -s http://127.0.0.1:${ELASTICSEARCH_PORT}/_cluster/health | grep -E '"status":"(green|yellow)"'
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 10

  kibana:
    image: ${KIBANA_IMAGE}
    hostname: ${KIBANA_HOST}
    ports:
      - ${KIBANA_PORT}
    env_file:
      - ./settings/docker_compose/.env
      - ./settings/kibana/.env
    volumes:
      - kibana_data:/usr/share/kibana/data
      - ./settings/kibana/provisioning:/etc/provisioning:ro
      - ./settings/kibana/entrypoint.sh:/etc/entrypoint.sh:ro
      - ./settings/docker_compose/wait:/etc/wait:ro
    entrypoint: /etc/entrypoint.sh
    depends_on:
      - kong
      - elasticsearch

  prometheus:
    image: ${PROMETHEUS_IMAGE}
    hostname: ${PROMETHEUS_HOST}
    ports:
      - ${PROMETHEUS_PORT}
    env_file:
      - ./settings/docker_compose/.env
    volumes:
      - prometheus_data:/prometheus
      - ./settings/prometheus/config.yaml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml # default of image
      - --storage.tsdb.path=/prometheus # default of image
      - --web.enable-otlp-receiver

  grafana:
    image: ${GRAFANA_IMAGE}
    hostname: ${GRAFANA_HOST}
    ports:
      - ${GRAFANA_PORT}
    env_file:
      - ./settings/docker_compose/.env
      - ./settings/grafana/.env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./settings/grafana/config.ini:/etc/grafana/grafana.ini:ro
      - ./settings/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./settings/grafana/entrypoint.sh:/etc/entrypoint.sh:ro
      - ./settings/docker_compose/wait:/etc/wait:ro
    entrypoint: /etc/entrypoint.sh
    depends_on:
      - kong
      - prometheus
      - jaeger
      - elasticsearch

  jaeger:
    image: ${JAEGER_IMAGE}
    hostname: ${JAEGER_HOST}
    ports:
      - ${JAEGER_UI_PORT}
      - ${JAEGER_OTEL_GRPC_PORT}
    env_file:
      - ./settings/docker_compose/.env
      - ./settings/jaeger/.env
    volumes:
      - ./settings/jaeger/entrypoint.sh:/etc/entrypoint.sh:ro
      - ./settings/docker_compose/wait:/etc/wait:ro
    entrypoint: /etc/entrypoint.sh
    depends_on:
      - kong
      - elasticsearch
      - prometheus

  kafka:
    image: ${KAFKA_IMAGE}
    hostname: ${KAFKA_HOST}
    ports:
      - ${KAFKA_BROKER_PORT}
      - ${KAFKA_CONTROLLER_PORT}
    env_file:
      - ./settings/docker_compose/.env
      - ./settings/kafka/.env
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: nc -z kafka ${KAFKA_BROKER_PORT}
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 10

  service_1:
    image: ${SERVICE_1_IMAGE}
    hostname: ${SERVICE_1_HOST}
    ports:
      - ${SERVICE_1_PORT}
    env_file:
      - ./settings/docker_compose/.env
      - ./settings/service_1/.env
    volumes:
      - ./settings/service_1/supervisord.conf:/etc/supervisord.conf:ro
      - ./settings/service_1/entrypoint.sh:/etc/entrypoint.sh:ro
      - ./settings/docker_compose/wait:/etc/wait:ro
    entrypoint: /etc/entrypoint.sh
    depends_on:
      - kong
      - otel_collector
      - kafka
      - service_2

  service_2:
    image: ${SERVICE_2_IMAGE}
    hostname: ${SERVICE_2_HOST}
    ports:
      - ${SERVICE_2_HTTP_PORT}
      - ${SERVICE_2_GRPC_PORT}
    env_file:
      - ./settings/docker_compose/.env
      - ./settings/service_2/.env
    volumes:
      - ./settings/service_2/supervisord.conf:/etc/supervisord.conf:ro
      - ./settings/service_2/entrypoint.sh:/etc/entrypoint.sh:ro
      - ./settings/docker_compose/wait:/etc/wait:ro
    entrypoint: /etc/entrypoint.sh
    depends_on:
      - kong
      - otel_collector
      - kafka

volumes:
  elasticsearch_data:
  kibana_data:
  prometheus_data:
  grafana_data:
  kafka_data:
