# =========================
# Supervisord
# =====
[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/dev/null

# =========================
# SupervisorCTL
# =====
[unix_http_server]
file=/run/supervisord.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisord.sock

# =========================
# Programs
# =====
[program:apis]
command=air --build.cmd "go build -o ./tmp/apis ./cmd/apis/main.go" --build.bin "./tmp/apis"
directory=/app
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:events]
command=air --build.cmd "go build -o ./tmp/events ./cmd/events/main.go" --build.bin "./tmp/events"
directory=/app
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
