default_stages: [pre-commit]
repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-mod-tidy

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.1.6
    hooks:
      - id: golangci-lint-config-verify
      - id: golangci-lint
        entry: golangci-lint run --new-from-rev HEAD --fix 2>/dev/null
      - id: golangci-lint-fmt
